name: "FlorisBoard NLP: Build"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/FUNDING.yml"
      - ".clang-format"
      - ".clang-tidy"
      - ".editorconfig"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"
  pull_request:
    branches: [ main ]

jobs:
  build_host:
    name: "Build for Desktop"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "Set up CMake and Ninja"
        uses: lukka/get-cmake@latest

      - name: "Toolchain setup"
        run: |
          $(pwd)/setup-toolchain.sh
      - name: "CMake: Configure release"
        run: |
          cmake --preset=release $(pwd)
      - name: "CMake: Build release"
        run: |
          cmake --build --preset=release $(pwd)

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: florisboard-nlp-artifacts
          path: build/release/bin/*
